SD-JWT representations
a-sit-plus/kmm-vc-library pull request #24
Opened 2023-10-23 17:54 UTC by nodh

Implements representing verifiable credentials in SD-JWT format, in addition to the more common JWT. Builds upon the selective disclosure mechanisms in our library used for ISO mobile driving licences.

2023-10-23 20:04 UTC, JesusMcCloud requested changes
Looks awesome! only change requests are in the review, the rest are comments/questions

2023-10-24 06:39 UTC, nodh commented on vclib-aries/src/commonTest/kotlin/at/asitplus/wallet/lib/aries/DummyCredentialDataProvider.kt
> +        subjectPublicKey: CryptoPublicKey?,
I'll guess it won't make a difference, since both, `CoseKey` and `CryptoPublicKey` are not specific to EC or RSA.

2023-10-24 07:57 UTC, nodh commented on vclib-aries/src/commonMain/kotlin/at/asitplus/wallet/lib/aries/IssueCredentialProtocol.kt
> +        // TODO Is there a way to transport the format, i.e. JWT-VC or SD-JWT?
There seems to be none, and since the ARIES protocol will go out of fashion, I don't think it's worth implementing a workaround.

2023-10-24 08:08 UTC, JesusMcCloud approved these changes
![image](https://github.com/a-sit-plus/kmm-vc-library/assets/5648377/c634e633-b765-48e1-87ea-8fb25be26c53)

2023-10-24 11:22 UTC, merged