add mirroring action
a-sit-plus/kmm-vc-library pull request #36
Opened 2024-02-15 06:56 UTC by JesusMcCloud

This PR adds the mirroring action to this repo.
Please do check if more files should be pruned before we merge this into main. E. g. do we really want to build it and consume minutes on a mac runner. isn't testing enough?

2024-02-15 14:01 UTC, nodh requested changes

2024-02-15 14:01 UTC, nodh commented on .github/workflows/mirror.yml
> +# This is a basic workflow to help you get started with Actions
shouldn't we remove this comments?

2024-02-15 14:03 UTC, nodh commented
> This PR adds the mirroring action to this repo. Please do check if more files should be pruned before we merge this into main. E. g. do we really want to build it and consume minutes on a mac runner. isn't testing enough?

Probably we should remove every action, since they're running here anyways.

2024-02-15 14:43 UTC, JesusMcCloud commented on .github/workflows/mirror.yml
> +# This is a basic workflow to help you get started with Actions
yes, i should

2024-02-19 16:08 UTC, JesusMcCloud commented on .github/workflows/mirror.yml
> +# This is a basic workflow to help you get started with Actions
removed

2024-02-19 16:08 UTC, merged