Thorough request object retrieval algorithm
a-sit-plus/kmm-vc-library pull request #45
Opened 2024-03-22 15:42 UTC by acrusage

Improved algorithm for retrieving AuthenticationResponseParameters as asked for in https://github.com/a-sit-plus/compose-wallet-app/pull/61#discussion_r1534006344

2024-03-28 07:41 UTC, JesusMcCloud requested changes
The implementation looks really good, but it would be nice to have both cases tested and not only the baseline one we hade before (even though it is important to keep it as regression test)

2024-03-28 09:08 UTC, acrusage commented
> The implementation looks really good, but it would be nice to have both cases tested and not only the baseline one we hade before (even though it is important to keep it as regression test)

I might need help with that, I'm not sure how to provide a dummy response to a HttpClient.get request

2024-03-28 15:36 UTC, acrusage commented
> The implementation looks really good, but it would be nice to have both cases tested and not only the baseline one we hade before (even though it is important to keep it as regression test)

fixed in commit 19b461408a25dfa5d43a8970ea973d2ee4db621b

2024-03-28 15:54 UTC, JesusMcCloud approved these changes

2024-03-29 15:47 UTC, merged

2024-04-02 07:57 UTC, nodh commented
I'm unhappy with the added dependency on `HttpClient` from  ktor ... is this really necessary?

2024-04-02 07:58 UTC, JesusMcCloud commented
how would you make an http request, without an http client?

2024-04-02 07:58 UTC, nodh commented on vclib-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidc/OidcSiopWallet.kt
> +private val HttpClient.asRequestObjectCandidateRetriever: RequestObjectCandidateRetriever
imho `as` as the prefix indicates a function, but this is a property

2024-04-02 14:31 UTC, acrusage commented
> > how would you make an http request, without an http client?
> 
> Why don't we leave that up to the client, i.e. the caller of our library, as it has been the case up until now?

fixed in commit 03a0cdd1303f7c2e0e17cbc4d665635566875f47 
prepared at pull request https://github.com/a-sit-plus/kmm-vc-library/pull/46 along with a fix for https://github.com/a-sit-plus/kmm-vc-library/pull/45#discussion_r1547342169