Feature/2024 04 03 improved presentation flexibility
a-sit-plus/kmm-vc-library pull request #49
Opened 2024-04-09 19:21 UTC by acrusage

This pull requests adds logic to handle a presentation definition more diligently, but this unfortunately leads to some changes in semantics expected from the "createPresentation" function before that. I hope the changes are reasonable, I tried following the guide from PresentationExchange at:
 - https://identity.foundation/presentation-exchange/spec/v2.0.0/#input-evaluation

Semantic changes to be approved:

### Presentation Submissions now only contain matches from input descriptors.
Each input descriptor matches to exactly one verifiable credential.
-> result.vp.verifiableCredentials now always has size 1!
Impacted Tests: 
- AgentTest."valid presentation is valid": change last "shouldHaveSize" to "1"
- ValidatorVpTest."valid parsed presentation should separate revoked and valid credentials": Change last "shouldHaveSize" to "issuedCredential.successful.size"

2024-04-10 15:43 UTC, JesusMcCloud requested changes
I have yet to reveiw the whole thing, but do try to get some existing test data for the json path impl (see my comment)

2024-04-10 15:43 UTC, JesusMcCloud commented on vclib/src/commonMain/kotlin/at/asitplus/wallet/lib/data/JSONPath.abnf
this belongs into `src/commonMain/resources`

2024-04-10 15:43 UTC, JesusMcCloud commented on vclib/src/commonTest/kotlin/at/asitplus/wallet/lib/data/JSONPathParserTest.kt
don't get me wrong, the JSONPath implementation looks impressive, but we really want a test data set, data-driven testing and property testing covering  random inputs with edge cases

2024-04-12 18:13 UTC, acrusage commented
Closed due to further work on JSONParser

2024-04-12 18:13 UTC, closed without merging

2024-04-15 08:03 UTC, nodh commented on vclib-openid/src/commonTest/kotlin/at/asitplus/wallet/lib/oidc/EudiwPidCredentialScheme.kt
You could also include https://github.com/a-sit-plus/eu-pid-credential for `commonTest` directly!