Feature/x509 san
a-sit-plus/kmm-vc-library pull request #63
Opened 2024-05-13 14:51 UTC by JesusMcCloud

Tests are missing, kmp-crypto is duct-tape-patched, so I am making it a draft.

@nodh Let me know what else you require before we can merge, given we want to get it deployed ASAP

2024-05-13 15:05 UTC, nodh requested changes
Please rebase your branch onto `develop`.
The implementation in `OdicSiopWallet` looks okay, but we'll also need an option to specify the correct metadata in `OidcSiopVerifier`

2024-05-13 15:05 UTC, nodh commented on vclib-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidc/OidcSiopWallet.kt
> +            || (params.parameters.clientIdScheme == OpenIdConstants.ClientIdSchemes.X509_SAN_DNS)
aren't both checks the same?

2024-05-13 15:05 UTC, nodh commented on vclib-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidc/OidcSiopWallet.kt
> +                        .also {
please reformat the logging statements to be ... somehow on one lin, so we can skim through the code more easily

2024-05-15 16:38 UTC, JesusMcCloud commented
Amended the verifier and (well the best way to put it is really:) changed the code until all the tests went green.

![image](https://github.com/a-sit-plus/kmm-vc-library/assets/5648377/a9d4fe2b-c661-4d90-9324-f3aad1acc688)

Still, I think it is a solid foundation to go through the diff and compare it to the spec.

2024-05-16 09:55 UTC, nodh approved these changes

2024-05-17 10:40 UTC, merged